name: Deploy

on:
  push:
    branches: [main]

permissions:
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Deployment
        uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          token: ${{ github.token }}
          environment: Production
          environment-url: https://digitaltwinfw.netlify.app
          production-environment: true
          initial-status: success
          description: "Deployed to Netlify"
